# Generated by Django 5.0.7 on 2024-08-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_serviceimage_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('event_name', models.CharField(max_length=100)),
                ('event_place', models.CharField(max_length=100)),
                ('event_time', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
